apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:fotis-sofoulis/tgnn_infrastructure.git
    targetRevision: HEAD
    path: app-directory
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true