ingress:
  enabled: true
  hosts:
    - jupyterhub.tgnnapp.local

global:
  safeToShowValues: true

singleuser:
  image:
    name: fotisofo/tgnn-jupyterhub
    tag: "3.4.1--rev1"
  cmd: null
  serviceAccountName: app-tgnnapp-spark
  #uid: 1001
  #fsGid: 1001
  networkPolicy:
    enabled: true
    ingress: []
    egress: []
    egressAllowRules:
      cloudMetadataServer: true 
      dnsPortsPrivateIPs: true
      nonPrivateIPs: true
      privateIPs: true
    interNamespaceAccessLabels: ignore
    allowedIngressPorts: []
