master:
  limits:
    cpu: 250m
    memory: 256Mi
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://spark.tgnnapp.local
worker:
  limits:
    cpu: 250m
    memory: 256Mi
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://spark.tgnnapp.local
  replicaCount: 2
ingress:
  enabled: true
  hostname: spark.tgnnapp.local