master:
  podSecurityContext:
    enabled: true 
  containerSecurityContext:
    enabled: true
  limits:
    cpu: 250m
    memory: 256Mi
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://spark.tgnnapp.local
worker:
  podSecurityContext:
    enabled: true
  containerSecurityContext:
    enabled: true
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://spark.tgnnapp.local
  replicaCount: 2
ingress:
  enabled: true
  hostname: spark.tgnnapp.local

image:
  registry: docker.io
  repository: yorgaraz/k8s-spark-dbg
  tag: 3.4.0-debian-11-r2--rev2
