master:
  limits:
    cpu: 250m
    memory: 256Mi
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://spark.tgnnapp.local
worker:
  initContainers:
    - name: spark-pi-test-client
      image: docker.io/bitnami/spark:3.4.0-debian-11-r2
      imagePullPolicy: Always
  configOptions:
    -Dspark.ui.reverseProxy=true
    -Dspark.ui.reverseProxyUrl=http://spark.tgnnapp.local
  replicaCount: 2
ingress:
  enabled: true
  hostname: spark.tgnnapp.local