apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-longhorn-setup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:fotis-sofoulis/tgnn_infrastructure.git
    targetRevision: HEAD
    path: app-constructs/longhorn/setup
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true