apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-tgnnapp-neo4j-setup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:fotis-sofoulis/tgnn_infrastructure.git
    targetRevision: HEAD
    path: app-constructs/neo4j/setup
  destination:
    server: https://kubernetes.default.svc
    namespace: tgnnapp
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true