apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-spark-dbg-as-deployment
  labels:
    app: k8s-spark-dbg-as-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-spark-dbg-as-deployment
  template:
    metadata:
      labels:
        app: k8s-spark-dbg-as-deployment
    spec:
      serviceAccountName: app-tgnnapp-spark
      containers:
      - name: k8s-spark-dbg-as-deployment
        image: "yorgaraz/k8s-spark-dbg:3.4.0-debian-11-r2--rev2"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false 
        env:
        - name: SPARK_MASTER_URL
          value: spark://app-tgnnapp-spark-master-svc:7077
        - name: SPARK_USER
          value: spark
        ports:
        - containerPort: 8080
        - containerPort: 7077
        - containerPort: 4040
        - containerPort: 18080
