apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-spark-dbg
  labels:
    app: k8s-spark-dbg
spec:
  replicas: 1
  serviceName: k8s-spark-dbg
  selector:
    matchLabels:
      app: k8s-spark-dbg
  template:
    metadata:
      labels:
        app: k8s-spark-dbg
    spec:
      serviceAccountName: app-tgnnapp-spark
      containers:
      - name: k8s-spark-dbg
        image: "fotisofo/tgnn-spark:3.4.1-debian-11-r4--rev1"
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
        env:
        - name: SPARK_MASTER_URL
          value: spark://app-tgnnapp-spark-master-svc:7077
        - name: SPARK_USER
          value: spark
        ports:
        - containerPort: 8080
        - containerPort: 7077
        - containerPort: 4040
        - containerPort: 18080
